# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Pet"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/rubocop --parallel
  # test:
  #   name: rspec
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:12
  #       ports: ["5432:5432"]
  #       env:
  #         POSTGRES_DB: pet_test
  #         POSTGRES_USER: pet
  #         POSTGRES_PASSWORD: postgres
  #     options: >-
          # --health-cmd pg_isready
          # --health-interval 10s
          # --health-timeout 5s
          # --health-retries 5
  #   env:
  #     RAILS_ENV: test
  #     DATABASE_URL: "postgres://pet:postgres@localhost:5432/pet_test"
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     # Add or replace dependency steps here
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
  #       with:
  #         bundler-cache: true
  #     # Add or replace database setup steps here
  #     - name: Set up database schema
  #       run: bin/rails db:schema:load
  #     # Add or replace test runners here
  #     - name: Run tests
  #       run: bin/rake
